### ISSUE TITLE
Getting daily notifications about new comments although that is not the case

### ISSUE THREAD

**Issue by Nilzor** [AndlyticsProject/andlytics#714] opened 2015-12-12 12:23 UTC
For 5 days in a row now I've gotten notifications about one of my apps having new comments. Each time I go in there are no new comments. Have cross checked with the Web interface. No comments since 2nd of December. Why am I getting notifications?

**Comment by willlunniss** [comment] 2015-12-14 07:50
Notifications are shown whenever the totals are different. It looks like they are making some changes retrospectively to older comments, which is why it isn't obvious what has changed. If it is still happening in a few days then we can investigate further, but it's not uncommon for things like this to happen.

**Comment by Nilzor** [comment] 2015-12-14 12:44
Ok. With "they" do you mean Google or the users themselves?

**Comment by udiidan** [comment] 2015-12-17 13:29
Having the same problem for over a week, and  though I know from the past the Google do make  changes to data from time to time, I don't recall getting so many false notifications.

**Comment by TheNephilim88** [comment] 2015-12-18 11:53
I have the same problem. But I think that this belongs to another problem. For my case, the shown total amount of comments is totally wrong. 2 or 3 weeks ago the correct fetching stopped working for me. 

For example the app shows me "146 comments" but actually the app has 4233 comments. So something is broken with fetching this number.

Another of my app is shown in app with "108 comments" but actually it has 130.

Unfortunately I have currently simply no time to take a look into the fetching-results.

**Comment by CannyDuck** [comment] 2015-12-23 12:05
I can confirm the isssue.

**Comment by foobar26** [comment] 2016-01-03 11:50
me too. Number of comments doesn't show the correct number and I continously get notification for changed / new comments, but nothing changed.

**Comment by mntgoat** [comment] 2016-01-07 21:20
For me the number of comments is changing daily and the + - is going crazy. It is almost as if it is showing the number of comments from the last 30 days (or less) or something like that.

**Comment by mntgoat** [comment] 2016-01-11 20:43
@willlunniss I don't think the issue was the retroactive changes they made. I have over 5k comments and the app thinks I have 173. It goes up and down every day, sometimes multiple times in the same day.

**Comment by willlunniss** [comment] 2016-01-11 22:05
Just had a look and I can see what has changed, will try to post a fix tomorrow.

**Comment by willlunniss** [comment] 2016-01-12 07:55
Just merged a fix, please test.

**Comment by TheNephilim88** [comment] 2016-01-12 08:06
Thanks @willlunniss , shows correct number of comments now.

**Comment by willlunniss** [comment] 2016-01-13 07:57
OK thanks for confirming. I'll try to find the time to do a release, worse case it will be at the weekend.

**Closed by willlunniss** 2016-01-13 07:57 UTC

**Comment by udiidan** [comment] 2016-01-23 19:00
Do you have an estimate when the release will be published in Google Play?

**Comment by mntgoat** [comment] 2016-01-27 16:58
@willlunniss or if not released on the Play Store, can we get an apk download link with the right signature so it doesn't conflict with the Play Store one? Thanks.

**Comment by willlunniss** [comment] 2016-01-27 20:28
Sorry about the delay, I've just pushed a release to Google Play so should be available shortly.

**Comment by mntgoat** [comment] 2016-01-27 23:42
Got the update, working well. Thanks.
