### ISSUE TITLE
No published app found

### ISSUE THREAD

**Issue by zhongzewu** [AndlyticsProject/andlytics#689] opened 2015-07-22 06:41 UTC
Today, i cann't get any published app informtion. At the beginning, i thought i could not get rating, but actually，fail to get any published app informtion.Does something happened  to change?

**Comment by zhongzewu** [comment] 2015-07-22 06:43
please help??

**Comment by willlunniss** [comment] 2015-07-22 07:01
Probably a duplicate of #688

**Closed by willlunniss** 2015-07-22 07:01 UTC
