### ISSUE TITLE
Stats won't update

### ISSUE THREAD

**Issue by alexblack** [AndlyticsProject/andlytics#688] opened 2015-07-20 19:57 UTC
Analytics attempts to get new stats but fails. It doesn't give an error like it did [a while back](https://github.com/AndlyticsProject/andlytics/issues/684).

After invoking refresh it displays the progress for a while. Then nothing. I expected the last updated time to change to now, instead its stuck at 4am, the last time it updated for me.

My app has had reviews since then.

**Comment by willlunniss** [comment] 2015-07-20 20:10
Can you post a logcat when you try to update

**Comment by alexblack** [comment] 2015-07-20 20:11
How do I do that?

**Comment by TheNephilim88** [comment] 2015-07-20 20:50
Problem is most probably because Google changed Ratings & Reviews-page and so parsing will fail. Log doesnt show that much, when refreshing:

07-20 22:46:27.260  10791-11939/? D/JsonParser﹕ Found 8 apps in JSON
07-20 22:46:27.260  10791-11939/? D/JsonParser﹕ com.myapp1: publishState=1
07-20 22:46:27.260  10791-11939/? D/JsonParser﹕ Adding incomplete app: com.myapp1
07-20 22:46:27.260  10791-11939/? D/JsonParser﹕ com.myapp2: publishState=1
07-20 22:46:27.260  10791-11939/? D/JsonParser﹕ Adding incomplete app: com.myapp2
...
07-20 22:46:27.260  10791-11939/? D/JsonParser﹕ Skipping app 4 with state != 1: package name=com.myapp4: state=2
07-20 22:46:27.260  10791-11939/? D/JsonParser﹕ com.myapp4: publishState=2
...
07-20 22:46:27.260  10791-11939/? D/JsonParser﹕ com.myapp5: publishState=1
07-20 22:46:27.260  10791-11939/? D/JsonParser﹕ Adding incomplete app: com.myapp5
07-20 22:46:27.260  10791-11939/? D/DevConsoleV2﹕ Found 5 apps for .........
07-20 22:46:27.260  10791-11939/? D/DevConsoleV2﹕ Incomplete packages: 5
07-20 22:46:27.260  10791-11939/? D/DevConsoleV2﹕ Got 5 incomplete apps, issuing details request
07-20 22:46:27.974  10791-11939/? D/JsonParser﹕ Found 5 apps in JSON
...
[same stuff as above... showing app-identification and "skipping"]
...
07-20 22:46:27.975  10791-11939/? D/DevConsoleV2﹕ Got 0 extra apps from details request

**Comment by willlunniss** [comment] 2015-07-21 06:50
OK, I can reproduce it as well now so I will have a look either tonight after work or tomorrow morning.

**Comment by willlunniss** [comment] 2015-07-22 19:26
Quick and dirty fix available for testing, please give it a go and report back if it works/doesn't (and include logs/json dumps if not).

**Comment by TheNephilim88** [comment] 2015-07-22 19:53
Thank you very much willlunniss.
Compiled version with your fix and everything is working! Also no strange stuff in log :+1:

**Comment by ardacuhadaroglu** [comment] 2015-07-23 04:46
So when will you publish the new andlytics?

**Comment by willlunniss** [comment] 2015-07-23 06:44
I might have time tonight, otherwise it may not be until the weekend unless one of the other project maintainers can help. It would be better if more than 1 other person had tested it as well.

**Comment by splatte** [comment] 2015-07-23 12:21
I compiled a version including your fix, too. It seems to be updating my free and paid apps just fine now and gives me "Incomplete packages: 0" in the logs where it was >0 before. thanks a lot @willlunniss!

**Comment by magnusgronbek** [comment] 2015-07-23 12:29
Is working ok. my apps were updated.

**Comment by yiankos** [comment] 2015-07-23 17:32
Where I can get fixed .apk? Thanks a lot.

**Comment by ardacuhadaroglu** [comment] 2015-07-23 19:59
You can checkout the code from https://github.com/willlunniss/andlytics .

**Comment by willlunniss** [comment] 2015-07-23 21:22
Thanks for the feedback, I've merged the PR and will push out a release as soon as I have a chance.

**Comment by willlunniss** [comment] 2015-07-24 06:56
I've push out a release to Google Play with the fix included.

**Closed by willlunniss** 2015-07-24 06:56 UTC
Labels: bug
